### PR TITLE
feat(pixel): add forget method to Pixel

### PR DESCRIPTION
**Pull request by beaufortfrancois**
With https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59233 now merged, this PR adds support for revoking access to the Pixel Bluetooth device.

Web Bluetooth Spec PR: https://github.com/WebBluetoothCG/web-bluetooth/pull/574

Please have a look @obasille

### CODE REVIEW

**Comment by obasille** [comment]
Thank you so much @beaufortfrancois!
Calling `BluetoothDevice.forget()` throws an "not a function" exception both with the latest Chrome and Canary builds (I just installed 101.0.4943.0).
What is your recommendation?

**Comment by beaufortfrancois** [comment]
I've updated code to include this catch. Thank you @obasille

**Comment by obasille** [comment]
> `chrome://flags/#enable-web-bluetooth-new-permissions-backend` is currently required as it is still an experimental feature. You can play with it at https://bluetoothdevice-forget.glitch.me/ for instance
> 
> See https://chromiumdash.appspot.com/commit/f100253a8279ef71a9ce84430744a4b951b98bc2 as well

Thank you for the update!
It works on Canary with the flag you mentioned. I imagine the change will be included in a future Chrome version.

**Comment by obasille** [comment]
Ah oups, just seeing your comment about needing Chrome 101 :)

**Comment by obasille** [comment]
Would you mind updating the commit to only include changes to `package.json` and `Pixel.ts`?
I'll update the lock file outside of the PR.

**Pull request merged**
